version: '3'

services:
  app-pgstac:
    container_name: stac-fastapi-pgstac
    image: ${API_IMAGE_URI}
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - RELOAD=false
      - ENVIRONMENT=local
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASS=${PGPASSWORD}
      - POSTGRES_DBNAME=${PGDATABASE}
      - POSTGRES_HOST_READER=${PGHOST}
      - POSTGRES_HOST_WRITER=${PGHOST}
      - POSTGRES_PORT=${PGPORT}
      - WEB_CONCURRENCY=10
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
    ports:
      - "8082:8082"
    logging:
      driver: awslogs
      options:
        awslogs-group: pgstac-fastapi
        awslogs-region: us-west-2
        awslogs-stream-prefix: app-pgstac
    command:
      python -m stac_fastapi.pgstac.app
