version: '3'
  database:
    container_name: stac-db
    image: ${DB_IMAGE_URI}
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
    ports:
      - "5433:5433"
    command: psql -f /sql/pgstac.sql

  pgstac-loadtestdata:
    image: ${API_IMAGE_URI}
    environment:
        - ENVIRONMENT=development
    command: 
        - "./scripts/wait-for-it.sh"
        - "--timeout=20"
        - "${STAC_URI}"
        - "--"
        - "python"
        - "/app/scripts/ingest_testdata.py"
        - "${STAC_URI}"
